import type { Product } from './types';
import { v4 as uuidv4 } from 'uuid';

// In a real application, this would be a database.
// For this demo, we're using an in-memory array.
export let products: Product[] = [
  {
    id: uuidv4(),
    name: 'Organic Avocados',
    description: 'Fresh, creamy Hass avocados, perfect for toast and guacamole. Grown without synthetic pesticides.',
    price: 2.5,
    unit: 'piece',
    stock: 150,
    expiryDate: new Date('2024-12-28'),
    imageUrl: 'https://picsum.photos/400/300?random=1',
    category: 'Fruits & Vegetables',
  },
  {
    id: uuidv4(),
    name: 'Sourdough Bread',
    description: 'Artisanal sourdough loaf with a tangy flavor and chewy crust. Baked fresh daily.',
    price: 5.99,
    unit: 'loaf',
    stock: 40,
    expiryDate: new Date('2024-11-05'),
    imageUrl: 'https://picsum.photos/400/300?random=2',
    category: 'Bakery',
  },
  {
    id: uuidv4(),
    name: 'Free-Range Eggs',
    description: 'One dozen large brown eggs from pasture-raised chickens. Rich, flavorful yolks.',
    price: 4.75,
    unit: 'dozen',
    stock: 80,
    expiryDate: new Date('2024-12-15'),
    imageUrl: 'https://picsum.photos/400/300?random=3',
    category: 'Dairy & Eggs',
  },
  {
    id: uuidv4(),
    name: 'Grass-Fed Ground Beef',
    description: 'One pound of 90% lean ground beef from grass-fed cattle. Ideal for burgers and sauces.',
    price: 9.99,
    unit: 'lb',
    stock: 65,
    expiryDate: new Date('2024-11-10'),
    imageUrl: 'https://picsum.photos/400/300?random=4',
    category: 'Meat & Seafood',
  },
  {
    id: uuidv4(),
    name: 'Almond Milk',
    description: 'Unsweetened almond milk, a great dairy-free alternative. Enriched with calcium and vitamin D.',
    price: 3.49,
    unit: 'carton',
    stock: 120,
    expiryDate: new Date('2025-02-01'),
    imageUrl: 'https://picsum.photos/400/300?random=5',
    category: 'Dairy & Eggs',
  },
  {
    id: uuidv4(),
    name: 'Organic Blueberries',
    description: 'Sweet and juicy organic blueberries, packed with antioxidants. Great for smoothies and snacks.',
    price: 6.20,
    unit: 'pint',
    stock: 90,
    expiryDate: new Date('2024-11-12'),
    imageUrl: 'https://picsum.photos/400/300?random=6',
    category: 'Fruits & Vegetables',
  },
  {
    id: uuidv4(),
    name: 'Cheddar Cheese Block',
    description: 'A sharp and aged cheddar cheese block, perfect for slicing, grating, or melting.',
    price: 7.50,
    unit: 'block',
    stock: 55,
    expiryDate: new Date('2025-03-20'),
    imageUrl: 'https://picsum.photos/400/300?random=7',
    category: 'Dairy & Eggs',
  },
  {
    id: uuidv4(),
    name: 'Whole Wheat Pasta',
    description: 'A healthy and delicious whole wheat pasta, rich in fiber and nutrients. Cooks in 10 minutes.',
    price: 2.99,
    unit: 'box',
    stock: 200,
    expiryDate: new Date('2025-10-15'),
    imageUrl: 'https://picsum.photos/400/300?random=8',
    category: 'Pantry',
  },
];
