import type { Product } from './types';

// Helper function to generate a random date within the next 2 years
const getRandomExpiryDate = () => {
  const today = new Date();
  const twoYearsFromNow = new Date();
  twoYearsFromNow.setFullYear(today.getFullYear() + 2);
  return new Date(today.getTime() + Math.random() * (twoYearsFromNow.getTime() - today.getTime()));
};

export const initialProducts: Omit<Product, 'id' | 'name_lowercase'>[] = [
  // Existing 8 products
  {
    name: 'Mì Hảo Hảo Tôm Chua Cay',
    description: 'Mì ăn liền vị tôm chua cay, một lựa chọn nhanh chóng và ngon miệng cho mọi nhà.',
    price: 4500,
    unit: 'gói',
    stock: 200,
    expiryDate: new Date('2025-12-31'),
    imageUrl: 'https://picsum.photos/400/300?random=1',
    category: 'Thực phẩm Khô',
  },
  {
    name: 'Nước mắm Nam Ngư 500ml',
    description: 'Nước mắm Nam Ngư 500ml, đậm đà hương vị truyền thống, là gia vị không thể thiếu trong bếp Việt.',
    price: 25000,
    unit: 'chai',
    stock: 80,
    expiryDate: new Date('2026-06-30'),
    imageUrl: 'https://picsum.photos/400/300?random=2',
    category: 'Gia vị',
  },
  {
    name: 'Dầu ăn Simply Đậu Nành 1L',
    description: 'Dầu đậu nành Simply 1 lít, tốt cho tim mạch, lựa chọn vàng cho các món chiên, xào.',
    price: 45000,
    unit: 'chai',
    stock: 100,
    expiryDate: new Date('2026-01-15'),
    imageUrl: 'https://picsum.photos/400/300?random=3',
    category: 'Gia vị',
  },
  {
    name: 'Sữa đặc Ông Thọ',
    description: 'Sữa đặc có đường Ông Thọ, lon 380g, dùng để pha cà phê, làm sữa chua hoặc làm bánh.',
    price: 22000,
    unit: 'lon',
    stock: 150,
    expiryDate: new Date('2025-10-20'),
    imageUrl: 'https://picsum.photos/400/300?random=4',
    category: 'Đồ hộp & Sữa',
  },
  {
    name: 'Bánh ChocoPie Orion',
    description: 'Hộp bánh ChocoPie Orion 12 cái, vỏ bánh mềm xốp phủ socola, thơm ngon khó cưỡng.',
    price: 54000,
    unit: 'hộp',
    stock: 70,
    expiryDate: new Date('2025-09-01'),
    imageUrl: 'https://picsum.photos/400/300?random=5',
    category: 'Bánh kẹo',
  },
  {
    name: 'Lốc 6 Coca-Cola',
    description: 'Lốc 6 lon Coca-Cola 330ml, giải khát sảng khoái tức thì, cho bữa ăn thêm trọn vẹn.',
    price: 50000,
    unit: 'lốc',
    stock: 120,
    expiryDate: new Date('2025-11-11'),
    imageUrl: 'https://picsum.photos/400/300?random=6',
    category: 'Đồ uống',
  },
  {
    name: 'Bột giặt OMO 4kg',
    description: 'Túi bột giặt OMO 4kg, trắng sáng, xoáy bay vết bẩn cứng đầu, hương thơm bền lâu.',
    price: 150000,
    unit: 'túi',
    stock: 50,
    expiryDate: new Date('2028-01-01'),
    imageUrl: 'https://picsum.photos/400/300?random=7',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Khăn giấy Pulppy',
    description: 'Lốc 10 cuộn khăn giấy Pulppy không lõi, mềm mại và dai, an toàn cho da nhạy cảm.',
    price: 75000,
    unit: 'lốc',
    stock: 90,
    expiryDate: new Date('2029-01-01'),
    imageUrl: 'https://picsum.photos/400/300?random=8',
    category: 'Hóa mỹ phẩm',
  },
  // New 42 products
  {
    name: 'Gạo ST25 Ông Cua 5kg',
    description: 'Gạo ST25 ngon nhất thế giới, túi 5kg, hạt dài, dẻo thơm, cơm ngọt vị.',
    price: 185000,
    unit: 'túi',
    stock: 60,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=9',
    category: 'Thực phẩm Khô',
  },
  {
    name: 'Tương ớt Chinsu 250g',
    description: 'Tương ớt Chinsu cay nồng, bùng vị mọi món ăn, chai 250g tiện lợi.',
    price: 12000,
    unit: 'chai',
    stock: 250,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=10',
    category: 'Gia vị',
  },
  {
    name: 'Sữa tươi Vinamilk 100% 1L',
    description: 'Sữa tươi tiệt trùng Vinamilk 100% có đường, hộp 1 lít, bổ sung canxi và vitamin.',
    price: 32000,
    unit: 'hộp',
    stock: 100,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=11',
    category: 'Đồ hộp & Sữa',
  },
  {
    name: 'Cà phê G7 3in1',
    description: 'Hộp cà phê hòa tan G7 3 trong 1, 21 gói, hương vị đậm đà, tỉnh táo tức thì.',
    price: 48000,
    unit: 'hộp',
    stock: 80,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=12',
    category: 'Đồ uống',
  },
  {
    name: 'Bánh gạo One One',
    description: 'Bánh gạo One One vị ngọt dịu, giòn tan, gói 150g, món ăn vặt yêu thích.',
    price: 15000,
    unit: 'gói',
    stock: 130,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=13',
    category: 'Bánh kẹo',
  },
  {
    name: 'Nước rửa chén Sunlight 750g',
    description: 'Nước rửa chén Sunlight chanh, đánh bay dầu mỡ, hương thơm tươi mát, chai 750g.',
    price: 22000,
    unit: 'chai',
    stock: 110,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=14',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Kem đánh răng Colgate 225g',
    description: 'Kem đánh răng Colgate MaxFresh ngừa sâu răng, cho hơi thở thơm mát, tuýp 225g.',
    price: 35000,
    unit: 'tuýp',
    stock: 95,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=15',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Xúc xích tiệt trùng Vissan',
    description: 'Gói 5 cây xúc xích heo tiệt trùng Vissan, giàu dinh dưỡng, tiện lợi cho bữa ăn nhẹ.',
    price: 28000,
    unit: 'gói',
    stock: 140,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=16',
    category: 'Thực phẩm Khô',
  },
  {
    name: 'Hạt nêm Knorr 400g',
    description: 'Hạt nêm Knorr từ thịt thăn, xương ống và tủy, cho món ăn tròn vị, gói 400g.',
    price: 26000,
    unit: 'gói',
    stock: 180,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=17',
    category: 'Gia vị',
  },
  {
    name: 'Lốc 6 lon Pepsi',
    description: 'Lốc 6 lon Pepsi 330ml, sảng khoái tột đỉnh, không calo, lựa chọn cho người ăn kiêng.',
    price: 48000,
    unit: 'lốc',
    stock: 115,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=18',
    category: 'Đồ uống',
  },
  {
    name: 'Bia Tiger Crystal',
    description: 'Thùng 24 lon bia Tiger Crystal 330ml, sảng khoái, uống không bị gắt, êm đằm.',
    price: 385000,
    unit: 'thùng',
    stock: 40,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=19',
    category: 'Đồ uống',
  },
  {
    name: 'Pate Cột Đèn Hải Phòng',
    description: 'Hộp pate gan Cột Đèn, đặc sản Hải Phòng, thơm béo ngậy, hộp 170g.',
    price: 45000,
    unit: 'hộp',
    stock: 65,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=20',
    category: 'Đồ hộp & Sữa',
  },
  {
    name: 'Nước tương Maggi 700ml',
    description: 'Nước tương Maggi đậu nành đậm đặc, chai 700ml, chấm hay nấu đều ngon.',
    price: 28000,
    unit: 'chai',
    stock: 85,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=21',
    category: 'Gia vị',
  },
  {
    name: 'Kẹo dẻo Chupa Chups',
    description: 'Gói kẹo dẻo Chupa Chups hương trái cây, dẻo dai, chua ngọt, gói 90g.',
    price: 18000,
    unit: 'gói',
    stock: 150,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=22',
    category: 'Bánh kẹo',
  },
  {
    name: 'Dầu gội Clear Bạc Hà',
    description: 'Chai dầu gội Clear Men Cool Sport bạc hà 630g, sạch gàu, mát lạnh.',
    price: 135000,
    unit: 'chai',
    stock: 55,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=23',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Trà xanh không độ',
    description: 'Chai trà xanh không độ 500ml, giải nhiệt cuộc sống, chứa EGCG tốt cho sức khỏe.',
    price: 10000,
    unit: 'chai',
    stock: 200,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=24',
    category: 'Đồ uống',
  },
  {
    name: 'Sữa chua Vinamilk có đường',
    description: 'Lốc 4 hộp sữa chua Vinamilk có đường, tốt cho hệ tiêu hóa, thơm ngon.',
    price: 24000,
    unit: 'lốc',
    stock: 130,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=25',
    category: 'Đồ hộp & Sữa',
  },
  {
    name: 'Băng vệ sinh Kotex',
    description: 'Gói băng vệ sinh Kotex Style siêu mỏng cánh 8 miếng, khô thoáng, chống tràn.',
    price: 20000,
    unit: 'gói',
    stock: 100,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=26',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Bột ngọt Ajinomoto 400g',
    description: 'Bột ngọt/Mì chính Ajinomoto, chiết xuất từ mía đường, gói 400g.',
    price: 27000,
    unit: 'gói',
    stock: 160,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=27',
    category: 'Gia vị',
  },
  {
    name: 'Phở bò ăn liền Vifon',
    description: 'Tô phở bò Vifon với gói thịt bò thật, hương vị như phở quán, 70g.',
    price: 15000,
    unit: 'tô',
    stock: 110,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=28',
    category: 'Thực phẩm Khô',
  },
  {
    name: 'Snack khoai tây Ostar',
    description: 'Snack khoai tây Ostar vị tảo biển, giòn rụm, thơm ngon, gói 60g.',
    price: 7000,
    unit: 'gói',
    stock: 300,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=29',
    category: 'Bánh kẹo',
  },
  {
    name: 'Nước tăng lực Sting',
    description: 'Chai nước tăng lực Sting dâu tây đỏ 330ml, bật năng lượng, sống bứt phá.',
    price: 10000,
    unit: 'chai',
    stock: 180,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=30',
    category: 'Đồ uống',
  },
  {
    name: 'Bánh mì sandwich ngọt',
    description: 'Gói bánh mì sandwich ngọt mềm, ăn liền hoặc kẹp thịt đều ngon.',
    price: 20000,
    unit: 'gói',
    stock: 50,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=31',
    category: 'Bánh kẹo',
  },
  {
    name: 'Nước lau sàn Lix',
    description: 'Nước lau sàn Lix hương hoa ly 1L, sạch bóng, ngát hương thơm.',
    price: 25000,
    unit: 'chai',
    stock: 70,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=32',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Thịt heo hộp Spam',
    description: 'Thịt heo hộp Spam Classic 340g, nhập khẩu Mỹ, chiên cơm hoặc ăn liền.',
    price: 85000,
    unit: 'hộp',
    stock: 45,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=33',
    category: 'Đồ hộp & Sữa',
  },
  {
    name: 'Đường Biên Hòa 1kg',
    description: 'Túi đường tinh luyện Biên Hòa 1kg, ngọt thanh, dễ hòa tan.',
    price: 28000,
    unit: 'túi',
    stock: 200,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=34',
    category: 'Gia vị',
  },
  {
    name: 'Miến dong Phú Hương',
    description: 'Miến dong Phú Hương yến tiệc, sợi dai ngon, gói 200g.',
    price: 22000,
    unit: 'gói',
    stock: 90,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=35',
    category: 'Thực phẩm Khô',
  },
  {
    name: 'Nước lọc Aquafina 500ml',
    description: 'Chai nước tinh khiết Aquafina 500ml, vị ngon của sự tinh khiết.',
    price: 5000,
    unit: 'chai',
    stock: 500,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=36',
    category: 'Đồ uống',
  },
  {
    name: 'Sữa tắm Lifebuoy 850g',
    description: 'Sữa tắm Lifebuoy bảo vệ vượt trội, chai 850g, sạch khuẩn, chăm sóc da.',
    price: 145000,
    unit: 'chai',
    stock: 60,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=37',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Cá hộp Ba Cô Gái',
    description: 'Cá nục sốt cà Ba Cô Gái, hộp 155g, món ăn quen thuộc trong bữa cơm gia đình.',
    price: 18000,
    unit: 'hộp',
    stock: 120,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=38',
    category: 'Đồ hộp & Sữa',
  },
  {
    name: 'Bánh quy Cosy Marie',
    description: 'Hộp bánh quy sữa Cosy Marie 288g, giòn xốp, thơm vị sữa.',
    price: 32000,
    unit: 'hộp',
    stock: 80,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=39',
    category: 'Bánh kẹo',
  },
  {
    name: 'Dao cạo râu Gillette',
    description: 'Vỉ 2 dao cạo râu Gillette Blue II Plus, cạo sạch, êm ái, không gây rát da.',
    price: 15000,
    unit: 'vỉ',
    stock: 150,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=40',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Trứng gà tươi vỉ 10',
    description: 'Vỉ 10 trứng gà ta tươi sạch, giàu dinh dưỡng, có thể chiên, luộc, kho.',
    price: 35000,
    unit: 'vỉ',
    stock: 30,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=41',
    category: 'Thực phẩm Tươi sống',
  },
  {
    name: 'Rau muống sạch VietGAP',
    description: 'Bó rau muống 300g, tiêu chuẩn VietGAP, tươi xanh, giòn ngon.',
    price: 15000,
    unit: 'bó',
    stock: 40,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=42',
    category: 'Thực phẩm Tươi sống',
  },
  {
    name: 'Thịt ba rọi heo CP',
    description: 'Khay 300g thịt ba rọi heo sạch CP, tươi ngon, có thể luộc, kho, nướng.',
    price: 48000,
    unit: 'khay',
    stock: 25,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=43',
    category: 'Thực phẩm Tươi sống',
  },
  {
    name: 'Dầu hào Maggi 350g',
    description: 'Chai dầu hào Maggi 350g, cho món xào thơm ngon, đậm vị.',
    price: 19000,
    unit: 'chai',
    stock: 90,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=44',
    category: 'Gia vị',
  },
  {
    name: 'Giấy vệ sinh An An',
    description: 'Lốc 6 cuộn giấy vệ sinh An An 3 lớp, mềm mại, tan nhanh trong nước.',
    price: 45000,
    unit: 'lốc',
    stock: 80,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=45',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Bim bim Oishi phồng tôm',
    description: 'Gói bim bim Oishi phồng tôm cay 40g, giòn tan, cay cay, ăn là ghiền.',
    price: 5000,
    unit: 'gói',
    stock: 400,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=46',
    category: 'Bánh kẹo',
  },
  {
    name: 'Nước giặt Ariel 3.2kg',
    description: 'Túi nước giặt Ariel Matic cho máy giặt cửa trước, sạch sâu, hương Downy, 3.2kg.',
    price: 210000,
    unit: 'túi',
    stock: 45,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=47',
    category: 'Hóa mỹ phẩm',
  },
  {
    name: 'Tương cà Chinsu 250g',
    description: 'Tương cà Chinsu, vị chua ngọt hài hòa, chấm khoai tây chiên, mì Ý đều ngon.',
    price: 11000,
    unit: 'chai',
    stock: 130,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=48',
    category: 'Gia vị',
  },
  {
    name: 'Phô mai Con Bò Cười',
    description: 'Hộp 8 miếng phô mai Con Bò Cười, giàu canxi và năng lượng, ăn với bánh mì.',
    price: 33000,
    unit: 'hộp',
    stock: 75,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=49',
    category: 'Đồ hộp & Sữa',
  },
  {
    name: 'Bia Heineken Silver',
    description: 'Thùng 24 lon bia Heineken Silver 330ml, vị nhẹ êm, dễ uống, cho cuộc vui thêm trọn vẹn.',
    price: 430000,
    unit: 'thùng',
    stock: 35,
    expiryDate: getRandomExpiryDate(),
    imageUrl: 'https://picsum.photos/400/300?random=50',
    category: 'Đồ uống',
  },
];
